# Copyright (C) 1995,1996 Robert de Bath <rdebath@cix.compulink.co.uk>
# This file is part of the Linux-8086 C library and is distributed
# under the GNU Library General Public License.
# 
# This file is automatically generated

OBJ=__syscall.o __syscall4.o __exit.o fork.o read.o write.o open.o 	\
    close.o wait4.o link.o unlink.o __execve.o chdir.o mknod.o 	\
    chmod.o chown.o __brk.o stat.o __lseek.o __getpid.o mount.o 	\
    umount.o setuid.o __getuid.o alarm.o fstat.o pause.o utime.o 	\
    chroot.o vfork.o access.o nice.o sleep.o sync.o kill.o rename.o 	\
    mkdir.o rmdir.o dup.o pipe.o __times.o dup2.o setgid.o __getgid.o 	\
    __signal.o fcntl.o ioctl.o reboot.o lstat.o symlink.o readlink.o 	\
    umask.o settimeofday.o gettimeofday.o select.o __readdir.o 	\
    fchown.o dlload.o setsid.o socket.o bind.o listen.o accept.o 	\
    connect.o knlvsn.o 


all: $(LIBC)($(OBJ))
	@$(RM) $(OBJ)

$(LIBC)($(OBJ)): syscall.dat
	$(CC) $(CFLAGS) -DL_$* syscall.c -c -o $*.o
	$(AR) $(ARFLAGS) $@ $*.o
