/*   0 */  sys_enosys,
/*   1 */  sys_exit,
/*   2 */  sys_fork,
/*   3 */  sys_read,
/*   4 */  sys_write,
/*   5 */  sys_open,
/*   6 */  sys_close,
/*   7 */  sys_wait4,
/*   8 */  sys_enosys, /* creat */
/*   9 */  sys_link,
/*  10 */  sys_unlink,
/*  11 */  sys_execve,
/*  12 */  sys_chdir,
/*  13 */  sys_enosys, /* time */
/*  14 */  sys_mknod,
/*  15 */  sys_chmod,
/*  16 */  sys_chown,
/*  17 */  sys_brk,
/*  18 */  sys_stat,
/*  19 */  sys_lseek,
/*  20 */  sys_getpid,
/*  21 */  sys_mount,
/*  22 */  sys_umount,
/*  23 */  sys_setuid,
/*  24 */  sys_getuid,
/*  25 */  sys_enosys, /* stime */
/*  26 */  sys_enosys, /* ptrace */
/*  27 */  sys_alarm,
/*  28 */  sys_fstat,
/*  29 */  sys_pause,
/*  30 */  sys_utime,
/*  31 */  sys_chroot,
/*  32 */  sys_vfork,
/*  33 */  sys_access,
/*  34 */  sys_nice,
/*  35 */  sys_sleep,
/*  36 */  sys_sync,
/*  37 */  sys_kill,
/*  38 */  sys_rename,
/*  39 */  sys_mkdir,
/*  40 */  sys_rmdir,
/*  41 */  sys_dup,
/*  42 */  sys_pipe,
/*  43 */  sys_times,
/*  44 */  sys_enosys, /* profil */
/*  45 */  sys_dup2,
/*  46 */  sys_setgid,
/*  47 */  sys_getgid,
/*  48 */  sys_signal,
/*  49 */  sys_enosys, /* getinfo */
/*  50 */  sys_fcntl,
/*  51 */  sys_enosys, /* acct */
/*  52 */  sys_enosys, /* phys */
/*  53 */  sys_enosys, /* lock */
/*  54 */  sys_ioctl,
/*  55 */  sys_reboot,
/*  56 */  sys_enosys, /* mpx */
/*  57 */  sys_lstat,
/*  58 */  sys_symlink,
/*  59 */  sys_readlink,
/*  60 */  sys_umask,
/*  61 */  sys_settimeofday,
/*  62 */  sys_gettimeofday,
/*  63 */  sys_select,
/*  64 */  sys_readdir,
/*  65 */  sys_enosys, /* insmod */
/*  66 */  sys_fchown,
/*  67 */  sys_dlload,
/*  68 */  sys_setsid,
/*  69 */  sys_socket,
/*  70 */  sys_bind,
/*  71 */  sys_listen,
/*  72 */  sys_accept,
/*  73 */  sys_connect,
/*  74 */  sys_knlvsn,
