# Copyright (C) 1995,1996 Robert de Bath <rdebath@cix.compulink.co.uk>
# This file is part of the Linux-8086 C library and is distributed
# under the GNU Library General Public License.
# 
# This file is automatically generated

OBJ=__exit.o fork.o vfork.o read.o write.o open.o close.o waitpid.o 	\
    creat.o link.o unlink.o execve.o chdir.o time.o __dv32_mknod.o 	\
    chmod.o chown.o lseek.o getpid.o mount.o umount.o setuid.o 	\
    getuid.o stime.o ptrace.o alarm.o pause.o utime.o access.o 	\
    nice.o ftime.o sync.o kill.o rename.o mkdir.o rmdir.o dup.o 	\
    pipe.o times.o setgid.o getgid.o signal.o geteuid.o getegid.o 	\
    acct.o ioctl.o fcntl.o setpgid.o ulimit.o umask.o chroot.o 	\
    __dv32_ustat.o dup2.o getppid.o getpgrp.o setsid.o sigaction.o 	\
    siggetmask.o sigsetmask.o setreuid.o setregid.o sigsuspend.o 	\
    sigpending.o sethostname.o setrlimit.o getrlimit.o getrusage.o 	\
    gettimeofday.o settimeofday.o getgroups.o setgroups.o __select.o 	\
    symlink.o readlink.o uselib.o swapon.o reboot.o __readdir.o 	\
    __mmap.o munmap.o truncate.o ftruncate.o fchmod.o fchown.o 	\
    getpriority.o setpriority.o statfs.o fstatfs.o ioperm.o __socketcall.o 	\
    setitimer.o getitimer.o __dv32_stat.o __dv32_lstat.o __dv32_fstat.o 	\
    iopl.o vhangup.o __vm86.o wait4.o swapoff.o sysinfo.o __ipc.o 	\
    fsync.o __sigreturn.o clone.o setdomainname.o uname.o adjtimex.o 	\
    mprotect.o sigprocmask.o getpgid.o fchdir.o bdflush.o sysfs.o 	\
    __personality.o setfsuid.o setfsgid.o __getdents.o flock.o 	\
    nanosleep.o 


CFLAGS=$(ARCH) $(CCFLAGS) $(DEFS)

all: $(LIBC)($(OBJ))
	@$(RM) $(OBJ)

$(LIBC)($(OBJ)): syscall.dat
	$(CC) $(CFLAGS) -DL_$* syscall.c -c -o $*.o
	$(AR) $(ARFLAGS) $@ $*.o
